CREATE DATABASE REGISTRO;

USE REGISTRO;

CREATE TABLE DATA(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    sexo VARCHAR(1) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    telefono VARCHAR(25) NOT NULL,
    direccion VARCHAR(500) NOT NULL
);

DESCRIBE DATA;